name: Force Delete All Deployments (Set inactive if needed)

on:
  workflow_dispatch:  # 手动触发

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List deployments
        id: list_deployments
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/deployments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Process and force-delete deployments
        run: |
          echo "Processing deployments..."

          deployments=$(echo '${{ steps.list_deployments.outputs.data }}' | jq -c '.[]')

          if [ -z "$deployments" ]; then
            echo "No deployments found."
            exit 0
          fi

          for deployment in $deployments; do
            id=$(echo "$deployment" | jq '.id')
            inactive_at=$(echo "$deployment" | jq -r '.inactive_at')
            environment=$(echo "$deployment" | jq -r '.environment')
            sha=$(echo "$deployment" | jq -r '.sha')

            echo "➡️ Deployment ID: $id | Environment: $environment | Inactive at: $inactive_at"

            if [ "$inactive_at" = "null" ]; then
              echo "⚠️ Deployment $id is still active — setting it to inactive..."

              curl -s -X POST \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github+json" \
                https://api.github.com/repos/${{ github.repository }}/deployments/$id/statuses \
                -d '{"state":"inactive"}'
              
              sleep 2  # 给 GitHub 一点时间更新状态
            fi

            echo "🗑 Deleting deployment ID: $id ..."
            curl -s -X DELETE \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/deployments/$id
          done

          echo "✅ All possible deployments processed."